<?php

namespace Database\Seeders;

use App\Models\RutaTarea;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RutaTareaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        RutaTarea::insert([
            ['ruta' => 'EL CARMEN - STO. DOMINGO', 'cliente_id' => 3],
            ['ruta' => 'PV. MALDONADO - TANDAYAPA', 'cliente_id' => 3],
            ['ruta' => 'LA CONCORDIA - PV. MALDONADO', 'cliente_id' => 3],
            ['ruta' => 'ST. DOMINGO - LA CONCORDIA', 'cliente_id' => 3],
            ['ruta' => 'P. PILAR - ST. DOMINGO', 'cliente_id' => 3],
            ['ruta' => 'LA CONCORDIA URBANO', 'cliente_id' => 3],
            ['ruta' => 'PUERTO QUITO URBANO', 'cliente_id' => 3],
            ['ruta' => 'PV. MALDONADO URBANO', 'cliente_id' => 3],
            ['ruta' => 'STO. DOMINGO URBANO', 'cliente_id' => 3],
            ['ruta' => 'SM. DE LOS BANCOS URBANO', 'cliente_id' => 3],
            ['ruta' => 'QUININDE - LA CONCORDIA', 'cliente_id' => 3],
            ['ruta' => 'ESMERALDAS - ATACAMES', 'cliente_id' => 3],
            ['ruta' => 'ESMERALDAS URBANO', 'cliente_id' => 3],
            ['ruta' => 'ATACAMES URBANO', 'cliente_id' => 3],
            ['ruta' => 'ESMERALDAS - TONCHIGUE', 'cliente_id' => 3],
            ['ruta' => 'ESMERALDAS - VICHE', 'cliente_id' => 3],
            ['ruta' => 'VICHE URBANO', 'cliente_id' => 3],
            ['ruta' => 'VICHE - QUININDE', 'cliente_id' => 3],
            ['ruta' => 'QUICAÑAR - AZOGUES', 'cliente_id' => 3],
            ['ruta' => 'ALAUSI - ZHUD', 'cliente_id' => 3],
            ['ruta' => 'ZHUD - CAÑAR', 'cliente_id' => 3],
            ['ruta' => 'CAÑAR URBANO', 'cliente_id' => 3],
            ['ruta' => 'ZHUD URBANO', 'cliente_id' => 3],
            ['ruta' => 'AZOGUES URBANO', 'cliente_id' => 3],
            ['ruta' => 'PEDERNALES URBANO', 'cliente_id' => 3],
            ['ruta' => 'PEDER-JAMA', 'cliente_id' => 3],
            ['ruta' => 'JAMA-URBANO', 'cliente_id' => 3],
            ['ruta' => 'JAMA-SAN VICENTE', 'cliente_id' => 3],
            ['ruta' => 'TONCHIGUE-AGUA CLARAS', 'cliente_id' => 3],
            ['ruta' => 'AGUAS CLARAS-BECHE', 'cliente_id' => 3],
            ['ruta' => 'MUISNE', 'cliente_id' => 3],
            ['ruta' => 'CHAMANGA', 'cliente_id' => 3],
            ['ruta' => 'GUALACEO - PAUTE', 'cliente_id' => 3],
            ['ruta' => 'GUALACEO URBANO', 'cliente_id' => 3],
            ['ruta' => 'LA UNÍÓN - GUALACEO', 'cliente_id' => 3],
            ['ruta' => 'LA UNIÓN - SIGSIG', 'cliente_id' => 3],
            ['ruta' => 'PAUTE - AZOGUES', 'cliente_id' => 3],
            ['ruta' => 'PAUTE URBANO', 'cliente_id' => 3],
            ['ruta' => 'SIGSIG - CHIGUINDA', 'cliente_id' => 3],
            ['ruta' => 'SIGSIG URBANO', 'cliente_id' => 3],
            ['ruta' => 'AZOGUES URBANO', 'cliente_id' => 3],
            ['ruta' => 'AZOGUES - CUENCA', 'cliente_id' => 3],
            ['ruta' => 'CUENCA - LA UNION', 'cliente_id' => 3],
            ['ruta' => 'STA ISABEL URBANO', 'cliente_id' => 3],
            ['ruta' => 'CUENCA URBANO', 'cliente_id' => 3],
            ['ruta' => 'GIRON URBANO', 'cliente_id' => 3],
            ['ruta' => 'CUENCA ICTO CRUZ URBANO', 'cliente_id' => 3],
            ['ruta' => 'CUENCA RICAURTE URBANO', 'cliente_id' => 3],
            ['ruta' => 'CUENCA LA RAYA URBANO', 'cliente_id' => 3],
            ['ruta' => 'MACHACHI - LATACUNGA URBANO', 'cliente_id' => 3],
            ['ruta' => 'LATACUNGA - ZUMBAGUA URBANO', 'cliente_id' => 3],
            ['ruta' => 'LATACUNGA - AMBATO', 'cliente_id' => 3],
            ['ruta' => 'LATACUNGA URBANO', 'cliente_id' => 3],
            ['ruta' => 'PUJILI URBANO', 'cliente_id' => 3],
            ['ruta' => 'ZUMBAGUA URBANO', 'cliente_id' => 3],
            ['ruta' => 'SAQUISILI URBANO', 'cliente_id' => 3],
            ['ruta' => 'AMBATO - RIOBAMBA', 'cliente_id' => 3],
            ['ruta' => 'SALCEDO URBANO', 'cliente_id' => 3],
            ['ruta' => 'MULALILLO URBANO', 'cliente_id' => 3],
            ['ruta' => 'PANSALEO URBANO', 'cliente_id' => 3],
            ['ruta' => 'STA ROSA TUNG. URBANO', 'cliente_id' => 3],
            ['ruta' => 'PORTOVELO - CHAGUARPAMBA', 'cliente_id' => 3],
            ['ruta' => 'BALSAS - PORTOVELO', 'cliente_id' => 3],
            ['ruta' => 'BALSAS URBANO', 'cliente_id' => 3],
            ['ruta' => 'CHAGUARPAMBA - BALSAS', 'cliente_id' => 3],
            ['ruta' => 'PIÑAS URBANO', 'cliente_id' => 3],
            ['ruta' => 'PORTOVELO URBANO', 'cliente_id' => 3],
            ['ruta' => 'ZARUMA URBANO', 'cliente_id' => 3],
            ['ruta' => 'PORTOVELO - ZARUMA', 'cliente_id' => 3],
            ['ruta' => 'CHAGUARPAMBA URBANO', 'cliente_id' => 3],
            ['ruta' => 'LA AVANZADA - BALSAS', 'cliente_id' => 3],
            ['ruta' => 'CHONE - F. ALFARO', 'cliente_id' => 3],
            ['ruta' => 'CHONE - ROCAFUERTE', 'cliente_id' => 3],
            ['ruta' => 'CHONE URBANO', 'cliente_id' => 3],
            ['ruta' => 'EL CARMEN URBANO', 'cliente_id' => 3],
            ['ruta' => 'TOSAGUA URBANO', 'cliente_id' => 3],
            ['ruta' => 'CHONE - CALCETA', 'cliente_id' => 3],
            ['ruta' => 'CALCETA URBANO', 'cliente_id' => 3],
            ['ruta' => 'CALCETA - PIMPIGUASI', 'cliente_id' => 3],
            ['ruta' => 'JUNIN URBANO', 'cliente_id' => 3],
            ['ruta' => 'CHONE  - TOSAGUA', 'cliente_id' => 3],
            ['ruta' => 'BHIA. CARAQUEZ URBANO', 'cliente_id' => 3],
            ['ruta' => 'F. ALFARO - EL CARMEN', 'cliente_id' => 3],
            ['ruta' => 'F. ALFARO URBANO', 'cliente_id' => 3],
            ['ruta' => 'LOJA - ZAMORA', 'cliente_id' => 3],
            ['ruta' => 'LOJA URBANO', 'cliente_id' => 3],
            ['ruta' => 'CATAMAYO - LOJA', 'cliente_id' => 3],
            ['ruta' => 'CATAMAYO URBANO', 'cliente_id' => 3],
            ['ruta' => 'CHAGUARPAMBA - CATAMAYO', 'cliente_id' => 3],
            ['ruta' => 'VILCABAMBA URBANO', 'cliente_id' => 3],
            ['ruta' => 'ZAMORA URBANO', 'cliente_id' => 3],
            ['ruta' => 'ARENILLAS URBANO', 'cliente_id' => 3],
            ['ruta' => 'STA. ROSA - ARENILLAS', 'cliente_id' => 3],
            ['ruta' => 'ARENILLAS - HUAQUILLAS', 'cliente_id' => 3],
            ['ruta' => 'HUAQUILLAS - LA AVANZADA', 'cliente_id' => 3],
            ['ruta' => 'LA AVANZADA - SANTA ROSA            ', 'cliente_id' => 3],
            ['ruta' => 'QUEVEDO - P. PILAR', 'cliente_id' => 3],
            ['ruta' => 'QUEVEDO URBANO', 'cliente_id' => 3],
            ['ruta' => 'LA MANA URBANO', 'cliente_id' => 3],
            ['ruta' => 'VALENCIA URBANO', 'cliente_id' => 3],
            ['ruta' => 'QUINSALOMA URBANO', 'cliente_id' => 3],
            ['ruta' => 'ZAPOTAL URBANO', 'cliente_id' => 3],
            ['ruta' => 'BUENA FE URBANO', 'cliente_id' => 3],
            ['ruta' => 'MOCACHE URBANO', 'cliente_id' => 3],
            ['ruta' => 'P. PILAR URBANO', 'cliente_id' => 3],
            ['ruta' => 'LAS NAVES URBANO', 'cliente_id' => 3],
            ['ruta' => 'QUEVEDO - VENTANAS', 'cliente_id' => 3],
            ['ruta' => 'MNG EMP - MNG MOCACHE', 'cliente_id' => 3],
            ['ruta' => 'MNG QVD - MNG MOCACHE', 'cliente_id' => 3],
            ['ruta' => 'MNG QVD - MNG QUINSALOMA', 'cliente_id' => 3],
            ['ruta' => 'MNG VEN - MNG QUINSALOMA', 'cliente_id' => 3],
            ['ruta' => 'GUAMOTE URBANO', 'cliente_id' => 3],
            ['ruta' => 'COLTA URBANO', 'cliente_id' => 3],
            ['ruta' => 'GUANO URBANO', 'cliente_id' => 3],
            ['ruta' => 'RIOBAMBA - ALAUSI', 'cliente_id' => 3],
            ['ruta' => 'YANTZAZA URBANO', 'cliente_id' => 3],
            ['ruta' => 'EL PANGUI - GUALAQUIZA', 'cliente_id' => 3],
            ['ruta' => 'EL PANGUI URBANO', 'cliente_id' => 3],
            ['ruta' => 'GUALAQUIZA - CHIGUINDA', 'cliente_id' => 3],
            ['ruta' => 'ZAMORA - PANGUI', 'cliente_id' => 3],
            ['ruta' => 'GUALAQUIZA URBANO', 'cliente_id' => 3],
            ['ruta' => 'LOS ENCUENTROS URBANO', 'cliente_id' => 3],
            ['ruta' => 'MACAS URBANO', 'cliente_id' => 3],
            ['ruta' => 'SUCUA URBANO', 'cliente_id' => 3],
            ['ruta' => 'LAGO AGRIO URBANO', 'cliente_id' => 3],
            ['ruta' => 'COCA URBANO', 'cliente_id' => 3],
            ['ruta' => 'JOYA DE LOS SACHAS URBANO            ', 'cliente_id' => 3],
            ['ruta' => 'SAMBORONDON URBANO', 'cliente_id' => 3],
            ['ruta' => 'SALITRE URBANO', 'cliente_id' => 3],
            ['ruta' => 'TARIFA URBANO', 'cliente_id' => 3],
            ['ruta' => 'DAULE - SAMBORONDON', 'cliente_id' => 3],
            ['ruta' => 'SAMBORONDON - MNG P.A.N', 'cliente_id' => 3],
            ['ruta' => 'VENTANAS URBANO', 'cliente_id' => 3],
            ['ruta' => 'PUEBLO VIEJO - VENTANAS', 'cliente_id' => 3],
            ['ruta' => 'CALUMA - PUEBLO VIEJO', 'cliente_id' => 3],
            ['ruta' => 'CALUMA URBANO', 'cliente_id' => 3],
            ['ruta' => 'CATARAMA URBANO', 'cliente_id' => 3],
            ['ruta' => 'BABAHOYO - SAN JUAN', 'cliente_id' => 3],
            ['ruta' => 'BABAHOYO - SIMON BOLIVAR', 'cliente_id' => 3],
            ['ruta' => 'BABAHOYO URBANO', 'cliente_id' => 3],
            ['ruta' => 'CALUMA - BABAHOYO', 'cliente_id' => 3],
            ['ruta' => 'ISLA BEJUCAL URBANO', 'cliente_id' => 3],
            ['ruta' => 'JUJAN URBANO', 'cliente_id' => 3],
            ['ruta' => 'PUEBLO VIEJO - SAN JUAN', 'cliente_id' => 3],
            ['ruta' => 'PUEBLO VIEJO URBANO', 'cliente_id' => 3],
            ['ruta' => 'SAN JUAN - VINCES', 'cliente_id' => 3],
            ['ruta' => 'TRES POSTES - BABAHOYO', 'cliente_id' => 3],
            ['ruta' => 'TRES POSTES URBANO', 'cliente_id' => 3],
            ['ruta' => 'VINCES URBANO', 'cliente_id' => 3],
            ['ruta' => 'SAN JUAN URBANO', 'cliente_id' => 3],
        ]);
    }
}
