<?php

namespace Database\Seeders;

use App\Models\FondosRotativos\Gasto\SubDetalleViatico;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SubDetalleViaticoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        SubDetalleViatico::insert([
            [
                'id_detalle_viatico' => 1,
                'descripcion' => 'DESAYUNO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 1,
                'descripcion' => 'ALMUERZO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 1,
                'descripcion' => 'MERIENDA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 1,
                'descripcion' => 'LOUNCH LIGTH',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 1,
                'descripcion' => 'AGUA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 1,
                'descripcion' => 'REFRIGERIO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 2,
                'descripcion' => 'DEPARTAMENTO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 2,
                'descripcion' => 'SUITE AMOBLADA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 2,
                'descripcion' => 'CASA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 2,
                'descripcion' => 'BODEGAS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 2,
                'descripcion' => 'GARAJES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 2,
                'descripcion' => 'GALPONES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 3,
                'descripcion' => 'RETROEXCAVADORAS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 3,
                'descripcion' => 'SONDA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 3,
                'descripcion' => 'MOTOSIERRA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 3,
                'descripcion' => 'GRÚAS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 4,
                'descripcion' => 'TICKET',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 4,
                'descripcion' => 'ENTRADA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 4,
                'descripcion' => 'DOCUMENTO U FACTURA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 5,
                'descripcion' => 'AUTOBÚS PÚBLICO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 6,
                'descripcion' => 'GENERADOR JP CONSTRURED',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 6,
                'descripcion' => 'GENERADOR NEDETEL - DIESEL',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 6,
                'descripcion' => 'GENERADOR NEDETEL - GASOLINA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 6,
                'descripcion' => 'GENERADOR NEDETEL - CANECAS DE COMBUSTIBLE',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 6,
                'descripcion' => 'GENERADOR NEDETEL - GALONES DE COMBUSTIBLE',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 7,
                'descripcion' => 'COLCHONES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 7,
                'descripcion' => 'BASE DE CAMAS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 7,
                'descripcion' => 'MATERIALES DE OFICINA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 7,
                'descripcion' => 'SUMINISTROS DE LIMPIEZA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 7,
                'descripcion' => 'PENDRIVE',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 7,
                'descripcion' => 'SELLOS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 7,
                'descripcion' => 'SOBRES PARA ENVIO DE VALIJA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 7,
                'descripcion' => 'BIDONES DE AGUA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 7,
                'descripcion' => 'MATERTIALES DE SEGURIDAD (ALCOHOL,MASCARILLAS)',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 7,
                'descripcion' => 'HERRAMIENTAS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 7,
                'descripcion' => 'MATERIALES DE CONSTRUCCIÒN',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 8,
                'descripcion' => 'CLIENTE',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 8,
                'descripcion' => 'PROPIO JP',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 9,
                'descripcion' => 'CONTRATISTA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 9,
                'descripcion' => 'TRABAJADOR DE LA EMPRESA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 10,
                'descripcion' => 'SOBRES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 10,
                'descripcion' => 'CARTONES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 10,
                'descripcion' => 'UNIFORMES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 10,
                'descripcion' => 'HERRAMIENTAS Y EQUIPOS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 10,
                'descripcion' => 'DOCUMENTACION',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 10,
                'descripcion' => 'SUMINISTROS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
             [
                'id_detalle_viatico' => 10,
                'descripcion' => 'ENVIO A NEDETEL',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 11,
                'descripcion' => 'MATERIALES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 11,
                'descripcion' => 'VEHICULO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 12,
                'descripcion' => 'HOTELES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 12,
                'descripcion' => 'APARTAMENTOS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 12,
                'descripcion' => 'HOSTALES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 12,
                'descripcion' => 'PENSIONES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 12,
                'descripcion' => 'ALBERGES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 13,
                'descripcion' => 'COPIAS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 14,
                'descripcion' => 'UNIFORMES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 14,
                'descripcion' => 'SABANA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 14,
                'descripcion' => 'MANTA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 14,
                'descripcion' => 'COLCHA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 14,
                'descripcion' => 'EDREDÓN',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 14,
                'descripcion' => 'ALMOHADAS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 14,
                'descripcion' => 'FORROS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 15,
                'descripcion' => 'ESTACIONAMIENTO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 15,
                'descripcion' => 'GARAJE PÚBLICO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 16,
                'descripcion' => 'TICKET DE TARIFA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 16,
                'descripcion' => 'FACTURA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 17,
                'descripcion' => 'CLIENTES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 17,
                'descripcion' => 'PROPIOS JP',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 18,
                'descripcion' => 'CLIENTES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 18,
                'descripcion' => 'PROPIOS JP',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 19,
                'descripcion' => 'ACTIVOS FIJOS DE LA EMPRESA JP',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 20,
                'descripcion' => 'CLIENTES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 20,
                'descripcion' => 'PROPIOS JP',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 21,
                'descripcion' => 'SECTOR RURAL',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 21,
                'descripcion' => 'SECTOR URBANO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 22,
                'descripcion' => 'TRAMITES A IDENTIDADES PUBLICAS - CLIENTES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 22,
                'descripcion' => 'TRAMITES A IDENTIDADES PUBLICAS - PROPIAS JP',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 22,
                'descripcion' => 'PAGOS DE SERVICIOS BÁSICOS DE ARRIENDOS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 22,
                'descripcion' => 'COMISIÓN DE BANCOS DE RETIRO DE DINERO DE FR',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 22,
                'descripcion' => 'PUBLICIDAD - RADIO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 22,
                'descripcion' => 'PUBLICIDAD - MEDIOS DIGITALES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 22,
                'descripcion' => 'PUBLICIDAD - PRENSA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 23,
                'descripcion' => 'SERVICIO DE MOVILIZACION',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 24,
                'descripcion' => 'CORRECTIVO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 24,
                'descripcion' => 'PERIODICO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 24,
                'descripcion' => 'PROGRAMADO - ALQUILADO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 24,
                'descripcion' => 'PROGRAMADO - PROPIO',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 25,
                'descripcion' => 'MULTAS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 25,
                'descripcion' => 'PÓLIZAS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 25,
                'descripcion' => 'MATRICULACIÓN - ALQUILADOS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 25,
                'descripcion' => 'MATRICULACIÓN - PROPIOS',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 26,
                'descripcion' => 'MATERIAL',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 26,
                'descripcion' => 'MANO DE OBRA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 27,
                'descripcion' => 'MANO DE OBRA',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
            [
                'id_detalle_viatico' => 27,
                'descripcion' => 'MATERIALES',
                'autorizacion' => 'SI',
                'id_estatus' => 1,
            ],
        ]);
    }
}
