@echo off
setlocal

rem Define las rutas de las carpetas que crearemos
set "basePath=.\storage\app"

rem Crear carpetas - Colocar aquí todas las carpetas a crear
mkdir "%basePath%\private\GestorArchivos"
mkdir "%basePath%\private\comprobantes"
mkdir "%basePath%\public\servicios"
mkdir "%basePath%\public\popup"
mkdir "%basePath%\public\tareas"
mkdir "%basePath%\public\subtareas"
mkdir "%basePath%\public\registrosTendidos"
mkdir "%basePath%\public\fotosPerfiles"
mkdir "%basePath%\public\firmas"
mkdir "%basePath%\public\trabajos"
mkdir "%basePath%\public\comprobantesViaticos"
mkdir "%basePath%\public\transferencias"
mkdir "%basePath%\public\transferenciasSaldo"
mkdir "%basePath%\public\seguimiento"
mkdir "%basePath%\public\archivos_seguimiento"
mkdir "%basePath%\public\justificacion_permiso_empleado"
mkdir "%basePath%\public\devoluciones\evidencias"
mkdir "%basePath%\public\pedidos\evidencias"
mkdir "%basePath%\public\clientes\logos"
mkdir "%basePath%\public\tickets"
mkdir "%basePath%\public\fotografias_actividades_realizadas"
mkdir "%basePath%\public\fotografias_seguimiento_tickets"
mkdir "%basePath%\public\archivos_seguimiento_tickets"
mkdir "%basePath%\public\fotografias_prestamo_empresarial"
mkdir "%basePath%\public\documentos_permiso_empleado"
mkdir "%basePath%\public\documentos_licencia_empleado"
mkdir "%basePath%\roles_de_pago"
mkdir "%basePath%\public\proveedores\calificaciones_proveedores"
mkdir "%basePath%\public\empresas"
mkdir "%basePath%\public\proveedores\empresas"
mkdir "%basePath%\public\configuracion_general"
mkdir "%basePath%\public\fotografias_novedades_ordenes_compras"
mkdir "%basePath%\public\ventasClaro\fotografias_novedades_ventas_claro"
mkdir "%basePath%\public\ventasClaro\novedades_ventas_claro"
mkdir "%basePath%\public\novedades_ordenes_compras"
mkdir "%basePath%\public\vehiculos"
mkdir "%basePath%\public\preingresos\archivos"
mkdir "%basePath%\public\fotografias_preingresos"
mkdir "%basePath%\public\transferencias_productos_empleados\archivos"
mkdir "%basePath%\public\carpeta_digital_empleados"
mkdir "%basePath%\public\vehiculos\fotografias_diarias"
mkdir "%basePath%\public\vehiculos\evidencias_incidentes"
mkdir "%basePath%\public\vehiculos\evidencias_ordenes_reparaciones"
mkdir "%basePath%\public\vehiculos\evidencias_tanqueo_combustible"
mkdir "%basePath%\public\vehiculos\evidencias_vehiculos_asignados"
mkdir "%basePath%\public\vehiculos\evidencias_vehiculos_transferidos"
mkdir "%basePath%\public\detalles_resultados_examenes\archivos"
mkdir "%basePath%\public\esquemas_vacunas\archivos"
mkdir "%basePath%\public\solicitudes_examenes\archivos"
mkdir "%basePath%\public\bodega\imagenesPermisosArmas"
mkdir "%basePath%\public\sso\incidentes"
mkdir "%basePath%\public\sso\seguimientos_incidentes"
mkdir "%basePath%\public\sso\accidentes"
mkdir "%basePath%\public\sso\solicitudes_descuentos"
mkdir "%basePath%\public\sso\inspecciones"

echo Carpetas creadas exitosamente.
pause
