#!/bin/bash

# Define la ruta base donde quieres crear las carpetas
BASE_PATH="./storage/app"

# Crear carpetas
mkdir -p "$BASE_PATH/private/GestorArchivos"
mkdir -p "$BASE_PATH/private/comprobantes"
mkdir -p "$BASE_PATH/public/servicios"
mkdir -p "$BASE_PATH/public/popup"
mkdir -p "$BASE_PATH/public/tareas"
mkdir -p "$BASE_PATH/public/subtareas"
mkdir -p "$BASE_PATH/public/registrosTendidos"
mkdir -p "$BASE_PATH/public/fotosPerfiles"
mkdir -p "$BASE_PATH/public/firmas"
mkdir -p "$BASE_PATH/public/trabajos"
mkdir -p "$BASE_PATH/public/comprobantesViaticos"
mkdir -p "$BASE_PATH/public/transferencias"
mkdir -p "$BASE_PATH/public/transferenciasSaldo"
mkdir -p "$BASE_PATH/public/seguimiento"
mkdir -p "$BASE_PATH/public/archivos_seguimiento"
mkdir -p "$BASE_PATH/public/justificacion_permiso_empleado"
mkdir -p "$BASE_PATH/public/devoluciones/evidencias"
mkdir -p "$BASE_PATH/public/pedidos/evidencias"
mkdir -p "$BASE_PATH/public/clientes/logos"
mkdir -p "$BASE_PATH/public/tickets"
mkdir -p "$BASE_PATH/public/fotografias_actividades_realizadas"
mkdir -p "$BASE_PATH/public/fotografias_seguimiento_tickets"
mkdir -p "$BASE_PATH/public/archivos_seguimiento_tickets"
mkdir -p "$BASE_PATH/public/fotografias_prestamo_empresarial"
mkdir -p "$BASE_PATH/public/documentos_permiso_empleado"
mkdir -p "$BASE_PATH/public/documentos_licencia_empleado"
mkdir -p "$BASE_PATH/roles_de_pago"
mkdir -p "$BASE_PATH/public/proveedores/calificaciones_proveedores"
mkdir -p "$BASE_PATH/public/empresas"
mkdir -p "$BASE_PATH/public/proveedores/empresas"
mkdir -p "$BASE_PATH/public/configuracion_general"
mkdir -p "$BASE_PATH/public/fotografias_novedades_ordenes_compras"
mkdir -p "$BASE_PATH/public/ventasClaro/fotografias_novedades_ventas_claro"
mkdir -p "$BASE_PATH/public/ventasClaro/novedades_ventas_claro"
mkdir -p "$BASE_PATH/public/novedades_ordenes_compras"
mkdir -p "$BASE_PATH/public/vehiculos"
mkdir -p "$BASE_PATH/public/preingresos/archivos"
mkdir -p "$BASE_PATH/public/fotografias_preingresos"
mkdir -p "$BASE_PATH/public/transferencias_productos_empleados/archivos"
mkdir -p "$BASE_PATH/public/carpeta_digital_empleados"
mkdir -p "$BASE_PATH/public/vehiculos/fotografias_diarias"
mkdir -p "$BASE_PATH/public/vehiculos/evidencias_incidentes"
mkdir -p "$BASE_PATH/public/vehiculos/evidencias_ordenes_reparaciones"
mkdir -p "$BASE_PATH/public/vehiculos/evidencias_tanqueo_combustible"
mkdir -p "$BASE_PATH/public/vehiculos/evidencias_vehiculos_asignados"
mkdir -p "$BASE_PATH/public/vehiculos/evidencias_vehiculos_transferidos"
mkdir -p "$BASE_PATH/public/detalles_resultados_examenes/archivos"
mkdir -p "$BASE_PATH/public/esquemas_vacunas/archivos"
mkdir -p "$BASE_PATH/public/solicitudes_examenes/archivos"

echo "Carpetas creadas exitosamente."
