<?php

namespace Database\Seeders\RecursosHumanos\SeleccionContratacion;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SolicitudPuestoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * php artisan db:seed --class=Database\Seeders\RecursosHumanos\SeleccionContratacion\SolicitudPuestoSeeder
     *
     * @return void
     */
    public function run()
    {
        $datos = [
            ['help desk', 1, 2, 2, NULL, '<div>En el departamento de Obra Civil necesitamos una persona para ayudante de obra civil y servicios varios</div><div>Requisitos</div><div>Conocimientos en:</div><div>Albañilería</div><div>Gasfitería</div><div>Pintura</div><div>Cerrajería</div><div>Soldadura</div><div>Trabajos en Gypsum&nbsp;&nbsp;</div><div>Responsabilidades propias del cargo:</div><div>• Solventar de manera rápida y profesional los problemas presentados en los trabajos realizados a los clientes (internos o externos).</div><div>• Cumplir con las normas y buenas prácticas de seguridad en el trabajo.</div><div>• Supervisar y controlar el uso adecuado de materiales según el objetivo de la obra, aplicando la norma establecida.</div><div>• Reportar de manera eficiente los trabajos realizados o las novedades presentadas al Coordinador o su Jefatura.</div><div>• Brindar soluciones efectivas y oportunas en los trabajos imprevistos de los clientes internos y externos.</div><div>• Realizar el cálculo de material para tareas y proyectos escalados sea de cliente interno externo.</div><div>• Realizar inspecciones, arreglos, tareas, requerimientos técnicos escalados al departamento sean internos o externos.</div><div>• Supervisar que el personal a su cargo cumpla con las tareas asignadas respetando los horarios y tiempos establecidos.</div><div>• Velar por el buen uso de la información, herramientas, materiales y activos de la compañía.</div><div>• Cumplir y hacer cumplir las responsabilidades y procedimientos del área</div><div><br></div>', '6 meses', '2024-07-11 17:24:55', '2024-07-11 18:54:01'],
            ['programador junior', 2, 2, 2, NULL, '<div>En el departamento de Obra Civil necesitamos una persona para ayudante de obra civil y servicios varios</div><div>Requisitos</div><div>Conocimientos en:</div><div>Albañilería</div><div>Gasfitería</div><div>Pintura</div><div>Cerrajería</div><div>Soldadura</div><div>Trabajos en Gypsum&nbsp;&nbsp;</div><div>Responsabilidades propias del cargo:</div><div>• Solventar de manera rápida y profesional los problemas presentados en los trabajos realizados a los clientes (internos o externos).</div><div>• Cumplir con las normas y buenas prácticas de seguridad en el trabajo.</div><div>• Supervisar y controlar el uso adecuado de materiales según el objetivo de la obra, aplicando la norma establecida.</div><div>• Reportar de manera eficiente los trabajos realizados o las novedades presentadas al Coordinador o su Jefatura.</div><div>• Brindar soluciones efectivas y oportunas en los trabajos imprevistos de los clientes internos y externos.</div><div>• Realizar el cálculo de material para tareas y proyectos escalados sea de cliente interno externo.</div><div>• Realizar inspecciones, arreglos, tareas, requerimientos técnicos escalados al departamento sean internos o externos.</div><div>• Supervisar que el personal a su cargo cumpla con las tareas asignadas respetando los horarios y tiempos establecidos.</div><div>• Velar por el buen uso de la información, herramientas, materiales y activos de la compañía.</div><div>• Cumplir y hacer cumplir las responsabilidades y procedimientos del área</div><div><br></div>', '1 año', '2024-07-11 17:24:55', '2024-07-11 18:54:01'],
            ['ayudante de obra civil', 1, 2, 2, NULL, '<div>En el departamento de Obra Civil necesitamos una persona para ayudante de obra civil y servicios varios</div><div>Requisitos</div><div>Conocimientos en:</div><div>Albañilería</div><div>Gasfitería</div><div>Pintura</div><div>Cerrajería</div><div>Soldadura</div><div>Trabajos en Gypsum&nbsp;&nbsp;</div><div>Responsabilidades propias del cargo:</div><div>• Solventar de manera rápida y profesional los problemas presentados en los trabajos realizados a los clientes (internos o externos).</div><div>• Cumplir con las normas y buenas prácticas de seguridad en el trabajo.</div><div>• Supervisar y controlar el uso adecuado de materiales según el objetivo de la obra, aplicando la norma establecida.</div><div>• Reportar de manera eficiente los trabajos realizados o las novedades presentadas al Coordinador o su Jefatura.</div><div>• Brindar soluciones efectivas y oportunas en los trabajos imprevistos de los clientes internos y externos.</div><div>• Realizar el cálculo de material para tareas y proyectos escalados sea de cliente interno externo.</div><div>• Realizar inspecciones, arreglos, tareas, requerimientos técnicos escalados al departamento sean internos o externos.</div><div>• Supervisar que el personal a su cargo cumpla con las tareas asignadas respetando los horarios y tiempos establecidos.</div><div>• Velar por el buen uso de la información, herramientas, materiales y activos de la compañía.</div><div>• Cumplir y hacer cumplir las responsabilidades y procedimientos del área</div><div><br></div>', null, '2024-07-11 17:24:55', '2024-07-11 18:54:01'],
            ['tecnico de mantenimiento', 2, 2, 2, NULL, '<div>En el departamento de Obra Civil necesitamos una persona para ayudante de obra civil y servicios varios</div><div>Requisitos</div><div>Conocimientos en:</div><div>Albañilería</div><div>Gasfitería</div><div>Pintura</div><div>Cerrajería</div><div>Soldadura</div><div>Trabajos en Gypsum&nbsp;&nbsp;</div><div>Responsabilidades propias del cargo:</div><div>• Solventar de manera rápida y profesional los problemas presentados en los trabajos realizados a los clientes (internos o externos).</div><div>• Cumplir con las normas y buenas prácticas de seguridad en el trabajo.</div><div>• Supervisar y controlar el uso adecuado de materiales según el objetivo de la obra, aplicando la norma establecida.</div><div>• Reportar de manera eficiente los trabajos realizados o las novedades presentadas al Coordinador o su Jefatura.</div><div>• Brindar soluciones efectivas y oportunas en los trabajos imprevistos de los clientes internos y externos.</div><div>• Realizar el cálculo de material para tareas y proyectos escalados sea de cliente interno externo.</div><div>• Realizar inspecciones, arreglos, tareas, requerimientos técnicos escalados al departamento sean internos o externos.</div><div>• Supervisar que el personal a su cargo cumpla con las tareas asignadas respetando los horarios y tiempos establecidos.</div><div>• Velar por el buen uso de la información, herramientas, materiales y activos de la compañía.</div><div>• Cumplir y hacer cumplir las responsabilidades y procedimientos del área</div><div><br></div>', '1 año', '2024-07-11 17:24:55', '2024-07-11 18:54:01'],
            ['fiscalizador de fibra optica', 2, 2, 2, NULL, '<div>En el departamento de Obra Civil necesitamos una persona para ayudante de obra civil y servicios varios</div><div>Requisitos</div><div>Conocimientos en:</div><div>Albañilería</div><div>Gasfitería</div><div>Pintura</div><div>Cerrajería</div><div>Soldadura</div><div>Trabajos en Gypsum&nbsp;&nbsp;</div><div>Responsabilidades propias del cargo:</div><div>• Solventar de manera rápida y profesional los problemas presentados en los trabajos realizados a los clientes (internos o externos).</div><div>• Cumplir con las normas y buenas prácticas de seguridad en el trabajo.</div><div>• Supervisar y controlar el uso adecuado de materiales según el objetivo de la obra, aplicando la norma establecida.</div><div>• Reportar de manera eficiente los trabajos realizados o las novedades presentadas al Coordinador o su Jefatura.</div><div>• Brindar soluciones efectivas y oportunas en los trabajos imprevistos de los clientes internos y externos.</div><div>• Realizar el cálculo de material para tareas y proyectos escalados sea de cliente interno externo.</div><div>• Realizar inspecciones, arreglos, tareas, requerimientos técnicos escalados al departamento sean internos o externos.</div><div>• Supervisar que el personal a su cargo cumpla con las tareas asignadas respetando los horarios y tiempos establecidos.</div><div>• Velar por el buen uso de la información, herramientas, materiales y activos de la compañía.</div><div>• Cumplir y hacer cumplir las responsabilidades y procedimientos del área</div><div><br></div>', '2 años', '2024-07-11 17:24:55', '2024-07-11 18:54:01'],
            ['tecnico de AACC', 2, 2, 2, NULL, '<div>En el departamento de Obra Civil necesitamos una persona para ayudante de obra civil y servicios varios</div><div>Requisitos</div><div>Conocimientos en:</div><div>Albañilería</div><div>Gasfitería</div><div>Pintura</div><div>Cerrajería</div><div>Soldadura</div><div>Trabajos en Gypsum&nbsp;&nbsp;</div><div>Responsabilidades propias del cargo:</div><div>• Solventar de manera rápida y profesional los problemas presentados en los trabajos realizados a los clientes (internos o externos).</div><div>• Cumplir con las normas y buenas prácticas de seguridad en el trabajo.</div><div>• Supervisar y controlar el uso adecuado de materiales según el objetivo de la obra, aplicando la norma establecida.</div><div>• Reportar de manera eficiente los trabajos realizados o las novedades presentadas al Coordinador o su Jefatura.</div><div>• Brindar soluciones efectivas y oportunas en los trabajos imprevistos de los clientes internos y externos.</div><div>• Realizar el cálculo de material para tareas y proyectos escalados sea de cliente interno externo.</div><div>• Realizar inspecciones, arreglos, tareas, requerimientos técnicos escalados al departamento sean internos o externos.</div><div>• Supervisar que el personal a su cargo cumpla con las tareas asignadas respetando los horarios y tiempos establecidos.</div><div>• Velar por el buen uso de la información, herramientas, materiales y activos de la compañía.</div><div>• Cumplir y hacer cumplir las responsabilidades y procedimientos del área</div><div><br></div>', '1 año', '2024-07-11 17:24:55', '2024-07-11 18:54:01'],
            ['asistente administrativo', 2, 2, 2, NULL, '<div>En el departamento de Obra Civil necesitamos una persona para ayudante de obra civil y servicios varios</div><div>Requisitos</div><div>Conocimientos en:</div><div>Albañilería</div><div>Gasfitería</div><div>Pintura</div><div>Cerrajería</div><div>Soldadura</div><div>Trabajos en Gypsum&nbsp;&nbsp;</div><div>Responsabilidades propias del cargo:</div><div>• Solventar de manera rápida y profesional los problemas presentados en los trabajos realizados a los clientes (internos o externos).</div><div>• Cumplir con las normas y buenas prácticas de seguridad en el trabajo.</div><div>• Supervisar y controlar el uso adecuado de materiales según el objetivo de la obra, aplicando la norma establecida.</div><div>• Reportar de manera eficiente los trabajos realizados o las novedades presentadas al Coordinador o su Jefatura.</div><div>• Brindar soluciones efectivas y oportunas en los trabajos imprevistos de los clientes internos y externos.</div><div>• Realizar el cálculo de material para tareas y proyectos escalados sea de cliente interno externo.</div><div>• Realizar inspecciones, arreglos, tareas, requerimientos técnicos escalados al departamento sean internos o externos.</div><div>• Supervisar que el personal a su cargo cumpla con las tareas asignadas respetando los horarios y tiempos establecidos.</div><div>• Velar por el buen uso de la información, herramientas, materiales y activos de la compañía.</div><div>• Cumplir y hacer cumplir las responsabilidades y procedimientos del área</div><div><br></div>', '2 años', '2024-07-11 17:24:55', '2024-07-11 18:54:01']
        ];


foreach($datos as $fila){
    DB::insert('INSERT INTO `rrhh_solicitudes_puestos_empleos` ( `nombre`, `tipo_puesto_id`, `autorizador_id`, `autorizacion_id`, `cargo_id`, `descripcion`, `anios_experiencia`, `created_at`, `updated_at`) VALUES(?,?,?,?,?,?,?,?,?)', $fila);
}
    }
}
