<?php

namespace Src\Config;

// Ayuda al frontend a seleccionar el icono de acuerdo al tipo
enum TiposNotificaciones: string{
    case INGRESO_MATERIALES = 'INGRESO DE MATERIALES';
    case PREINGRESO = 'PREINGRESO DE MATERIALES';
    case PEDIDO = 'PEDIDO';
    case DEVOLUCION = 'DEVOLUCION';
    case AUTORIZACION_GASTO = 'AUTORIZACION GASTO';
    case TRANSFERENCIA_SALDO = 'TRANSFERENCIA DE SALDO';
    // Tareas
    case TAREA = 'TAREA';
    case SUBTAREA = 'SUBTAREA';
    case TRANSFERENCIA_PRODUCTOS = 'TRANSFERENCIA DE PRODUCTOS';
    // Tickets
    case EGRESO = 'EGRESO';
    case TICKET = 'TICKET';
    case PERMISO_EMPLEADO = 'PERMISO EMPLEADO';
    case PRESTAMO_EMPRESARIAL = 'PRESTAMO EMPRESARIAL';
    case LICENCIA_EMPLEADO = 'LICENCIA EMPLEADO';
    case SOLICITUD_PRESTAMO_EMPRESARIAL = 'SOLICITUD PRESTAMO EMPRESARIAL';
    case VACACION = 'VACACION';
    //compras y proveedores
    case PREORDEN = 'PREORDEN';
    case ORDEN_COMPRA = 'ORDEN_COMPRA';
    case PROFORMA = 'PROFORMA';
    case PREFACTURA = 'PREFACTURA';
    case PROVEEDOR = 'PROVEEDOR';

    //vehiculos
    case MATRICULA = 'MATRICULA';
    case SEGURO_VEHICULAR = 'SEGURO_VEHICULAR';
    case BITACORA_VEHICULAR = 'BITACORA VEHICULAR';
    case BITACORA_VEHICULAR_ADVERTENCIA = 'ADVERTENCIA BITACORA VEHICULAR';
    case MULTA_CONDUCTOR = 'MULTA_CONDUCTOR';
    case ASIGNACION_VEHICULO = 'ASIGNACION_VEHICULO';
    case TRANSFERENCIA_VEHICULO = 'TRANSFERENCIAS_VEHICULOS';
    case ORDEN_REPARACION_VEHICULO = 'ORDEN_REPARACION_VEHICULO';
    case MANTENIMIENTOS_VEHICULOS = 'MANTENIMIENTO DE VEHICULOS';
    // medico
    case SOLICITUD_EXAMEN = 'SOLICITUD DE EXAMEN';
    case DIAS_DESCANSO = 'DIAS DE DESCANSO';
    // Activos fijos
    case ENTREGA_ACTIVO_FIJO = 'ENTREGA ACTIVO FIJO';
}
